/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Background: typeof import('./src/components/widget/background/index.vue')['default']
    Config: typeof import('./src/components/widget/gauge/config.vue')['default']
    ElCarousel: typeof import('element-plus/es')['ElCarousel']
    ElCarouselItem: typeof import('element-plus/es')['ElCarouselItem']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCheckboxGroup: typeof import('element-plus/es')['ElCheckboxGroup']
    ElColorPicker: typeof import('element-plus/es')['ElColorPicker']
    ElementCarousel: typeof import('./src/components/widget/element-carousel/index.vue')['default']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    Gauge: typeof import('./src/components/widget/gauge/index.vue')['default']
    Image: typeof import('./src/components/widget/image/index.vue')['default']
    LineChart: typeof import('./src/components/widget/line-chart/index.vue')['default']
    Pie: typeof import('./src/components/widget/pie/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Text: typeof import('./src/components/widget/text/index.vue')['default']
    VantButton: typeof import('./src/components/widget/vant-button/index.vue')['default']
    VantSlider: typeof import('./src/components/widget/vant-slider/index.vue')['default']
    VantSwipe: typeof import('./src/components/widget/vant-swipe/index.vue')['default']
    VantSwiper: typeof import('./src/components/widget/vant-swiper/index.vue')['default']
    Video: typeof import('./src/components/widget/video/index.vue')['default']
  }
}
